services:
  postgres-db:
    image: postgres:latest
    container_name: fase5-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2023!
      - POSTGRES_ENCONDING=UTF-8
    ports:
      - 5432:5432
    volumes:
      - ./01-database.sql:/docker-entrypoint-initdb.d/01-database.sql
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fase5network

  postgres-db-autenticador:
    image: postgres:latest
    container_name: fase5-postgres-aut
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2023!
      - POSTGRES_ENCONDING=UTF-8
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fase5network


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 15432:80
    links:
      - postgres-db
    networks:
      - fase5network

  srv-discovery:
    build: './srvDiscovery'
    container_name: srv-discovery
    ports:
      - 8761:8761
    networks:
      - fase5network


  srv-gateway:
    build: './srvGateway'
    container_name: srv-gateway
    ports:
      - 8080:8080
    depends_on:
      - srv-discovery
    networks:
      - fase5network


  srv-cliente:
    build: './srvCliente'
    container_name: srv-cliente
    ports:
      - 9510:9510
    depends_on:
      - postgres-db
      - pgadmin
      - srv-discovery
      - srv-gateway
    networks:
      - fase5network

  srv-item:
    build: './srvItem'
    container_name: srv-item
    ports:
      - 9511:9511
    depends_on:
      - postgres-db
      - srv-discovery
      - srv-gateway
    networks:
      - fase5network

  srv-autenticacao:
    build: './srvAutenticacao'
    container_name: srv-autenticacao
    ports:
      - 9898:9898
    depends_on:
      - postgres-db
      - srv-discovery
      - srv-gateway
    networks:
      - fase5network

networks:
  fase5network:
    external: true
