spring:
  application:
    name: srvAutenticacao
  # Postgresql
  datasource:
    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    hikari:
      schema: dbusuarios
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbusuarios
    show-sql: false

openapi:
  service:
    title: service-cliente doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /clientes/api-docs
  swagger-ui:
    path: /clientes/swagger-ui.html

# Others
server:
  port: 9898

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka

api:
  security:
    token:
      secret: ${JWT_SECRET:batman batman batman}
