spring:
  application:
    name: srvCliente
# Postgresql
  datasource:
    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    hikari:
      schema: dbClientes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbClientes
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true

openapi:
  service:
    title: service-cliente doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /clientes/api-docs
  swagger-ui:
    path: /clientes/swagger-ui.html

# Others
server:
  port: 9510

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUR_DEFAULTZONE:http://srv-discovery:8761/eureka}

# Viacep - busca endereco
appviacep:
  receive:
    name: viacep
    url: https://viacep.com.br/ws/
