spring:
  application:
    name: srvGateway
  cloud:
    gateway:
      routes:
        - id: tbsrvcliente
          uri: lb://srvcliente
          predicates:
            - Path=/clientes/**

server:
  port: 8080

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
