spring:
  application:
    name: srvGateway
  cloud:
    gateway:
      routes:
        - id: tbsrvcliente
          uri: lb://srvcliente
          predicates:
            - Path=/clientes/**
          filters:
            - AuthenticationFilter

        - id: tbsrvautenticacao
          uri: lb://srvautenticacao
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: tbsrvautenticacaousers
          uri: lb://srvautenticacao
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: tbsrvpagamento
          uri: lb://srvpagamento
          predicates:
            - Path=/pagamento/**
          filters:
            - AuthenticationFilter

        - id: tbsrvprodutos
          uri: lb://srvitem
          predicates:
            - Path=/itens/**
          filters:
            - AuthenticationFilter

        - id: tbsrvcarrinho
          uri: lb://srvcarrinho
          predicates:
            - Path=/carrinhos/**
          filters:
            - AuthenticationFilter


server:
  port: 8080

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://srv-discovery:8761/eureka

# Swagger
springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - url: /auth/api-docs
        name: Autenticacao Service
      - url: /users/api-docs
        name: Usuario Service
      - url: /clientes/api-docs
        name: Cliente Service
      - url: /itens/api-docs
        name: Produtos Service
      - url: /pagamentos/api-docs
        name: Pagamentos Service
      - url: /carrinhos/api-docs
        name: Carrinhos Service

api:
  security:
    token:
      secret: ${JWT_SECRET:batman batman batman}