spring:
  application:
    name: srvGateway
  cloud:
    gateway:
      routes:
        - id: tbsrvcliente
          uri: lb://srvcliente
          predicates:
            - Path=/clientes/**
        - id: tbsrvclienteswagger
          uri: lb://srvcliente
          predicates:
            - Path=/clientes/api-docs
            - Method=GET

        - id: tbsrvpagamento
          uri: lb://srvpagamento
          predicates:
            - Path=/pagamentos/**

        - id: tbsrvprodutos
          uri: lb://srvitem
          predicates:
            - Path=/itens/**
        - id: tbsrvprodutoswagger
          uri: lb://srvitem
          predicates:
            - Path=/itens/api-docs
            - Method=GET

server:
  port: 8080

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://srv-discovery:8761/eureka

# Swagger
springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - url: /clientes/api-docs
        name: Cliente Service
      - url: /itens/api-docs
        name: Produtos Service
      - url: /pagamentos/api-docs
        name: Pagamentos Service
