spring:
  application:
    name: srvItem
  # Postgresql
  datasource:
    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    hikari:
      schema: dbprodutos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbprodutos
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true

openapi:
  service:
    title: service-item doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /itens/api-docs
  swagger-ui:
    path: /itens/swagger-ui.html

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUR_DEFAULTZONE:http://srv-discovery:8761/eureka}

# Others
server:
  port: 9511
