spring:
  application:
    name: srvPagamento
  # Postgresql
  datasource:
    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}
    hikari:
      schema: dbPagamentos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbPagamentos
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true

openapi:
  service:
    title: service-pagamento doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /pagamento/api-docs
  swagger-ui:
    path: /pagamento/swagger-ui.html

# Others
server:
  port: 9513