spring:
  application:
    name: srvCarrinho
  # Postgresql
  datasource:
    url: ${SP_DTSRC_URL:jdbc:postgresql://postgres-db:5432/fase5}
    username: ${SP_DTSRC_USERNAME:postgres}
    password: ${SP_DTSRC_PASSWORD:Postgres2023!}

    ## url: jdbc:postgresql://localhost:5432/postgres
    ## username: postgres
    ## password: 102030


    hikari:
      schema: dbpedidos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dbpedidos
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    generate-ddl: true

openapi:
  service:
    title: service-carrinho doc
    version: 1.0.0
    url: localhost:8080
springdoc:
  api-docs:
    path: /carrinhos/api-docs
  swagger-ui:
    path: /carrinhos/swagger-ui.html

# Others
server:
  port: 9515

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUR_DEFAULTZONE:http://srv-discovery:8761/eureka}
    ##  defaultZone: http://localhost:8761/eureka

# Viacep - busca endereco
appviacep:
  receive:
    name: viacep
    url: https://viacep.com.br/ws/
